### PR TITLE
Index: Remove Pledgie links from home page

### PR DESCRIPTION
**Pull request by Arkni**
Removed the Pledgie link from the home page as discussed in Twitter DM

/cc @staabm

### CODE REVIEW

**Comment by staabm** [comment]
thx.

added a bit more context from our twitter conversation into the commit mesage.

**Comment by jzaefferer** [comment]
How do you feel about replacing that with an oldschool PayPal-donate button or something like that? The pledgie campaign had tried up quite some time ago, but over the years it covered the hosting costs.

**Comment by jzaefferer** [comment]
The widget/link is still on https://jqueryvalidation.org/ - I guess this change wasn't deployed?

**Comment by staabm** [comment]
yep no deployment occured yet. feel free to add a paypal or whatever button and re-deploy

**Comment by jzaefferer** [comment]
Let's deploy this as-is for now. At least to get rid of the dead link

**Comment by jzaefferer** [comment]
@staabm can you deploy this? The site still shows the dead Pledgi link

**Comment by jzaefferer** [comment]
"The plugin is written and maintained by Jörn Zaefferer, a member of the jQuery team, lead developer on the jQuery UI team and maintainer of QUnit. It was started back in the early days of jQuery in 2006, and updated and improved since then.", that might be worth an update, too...

**Comment by staabm** [comment]
Will di today

**Comment by staabm** [comment]
done.

**Pull request merged**
