### PR TITLE
Use https

### PR DESCRIPTION
**Pull request by Arkni**
In this PR, I:
* Update some links to use `https`
* Use the latest version of `jquery-validation` for demos
* Update links to the new organization

### CODE REVIEW

**Comment by staabm** [comment]
could you prefix the separate commits with the corresponding category ("Entries:" etc)?

**Comment by Arkni** [comment]
Done!

**Comment by staabm** [comment]
thx

**Comment by staabm** [comment]
let me redeploy the docs and see if I can update the demos in a few mins

**Pull request merged**
